Repository stm32-rs/stm32l0xx-hal, pull requests merged in 2021-03, with the labels that each got.

#131 Adds support of LSE clocking to LPUART
  Cargo.toml
  examples/serial_lse.rs
  src/rcc.rs
  src/serial.rs
Labels: status: waiting on author

#154 Add a CHANGELOG
  .gitattributes
  CHANGELOG.md
Labels: chore

#152 Add `Timer::new` to create timer without starting
  CHANGELOG.md
  src/timer.rs
Labels: status: waiting for review
